subtitle = "Un blog sur la technologie, la programmation et plus encore."
menuMore = "Voir plus"
readMore = "Lire plus"
readOtherPosts = "Lire une autre publication"
newerPosts = "Nouvelles publication"
olderPosts = "Anciennes publication"
missingContentMessage = "Page non trouvé..."
missingBackButtonLabel = "Retour à la page principale"
minuteReadingTime = "min de lecture"
words = "mots"
updatedDatePrefix = "Mis à jour"
